export const infoData = [
  {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Members Only',
    headline: 'Gain access to insane opportunities',
    description:
      'Break into a circle of professionals dedicted to personal growth and supporting one another to win',
    buttonLabel: 'Get started',
    imgStart: false,
    img: '/images/svg-1.svg',
    alt: 'Group',
    dark: true,
    primary: true,
    darkText: false,
    fontSize: 'fontBig',
  },
  {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Members Only',
    headline: 'Gain access to insane opportunities',
    description:
      'Break into a circle of professionals dedicted to personal growth and supporting one another to win',
    buttonLabel: 'Get started',
    imgStart: true,
    img: '../../images/svg-1.svg',
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
    fontSize: 'big',
  },
];
